name: Sync with upstream

on:
  schedule:
    - cron: '0 6 * * *'   # tous les jours à 6h UTC
  workflow_dispatch:

jobs:
  sync_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Sync upstream into main
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: twentyhq/twenty

  sync_capsule:
    needs: sync_main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: capsule
          persist-credentials: false

      - name: Merge main into capsule
        run: |
          git merge origin/main --no-edit || echo "Nothing to merge"
          git push origin capsule
